### ISSUE TITLE
Perpetual diffs with instatus_component

### ISSUE THREAD

**Issue by jarinom** [paydaycay/terraform-provider-instatus#1]
I'm experiencing perpetual diffs with instatus_component resources.

### Terraform Version
```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/grafana/grafana v2.14.3
+ provider registry.terraform.io/paydaycay/instatus v0.1.4
```

### Affected Resource(s)
- instatus_component

### Terraform Configuration Files
```hcl
resource "instatus_component" "spaceship_ratetiger" {
  page_id     = var.instatus_page_id
  grouped     = true
  group       = instatus_component.spaceship.name
  name        = "Ratetiger integration"
  show_uptime = true
  status      = "OPERATIONAL"
  order       = 37
}
```

### Debug Output
```
  # instatus_component.spaceship_ratetiger will be updated in-place
  ~ resource "instatus_component" "spaceship_ratetiger" {
      ~ group_id     = "retracted" -> (known after apply)
        id           = "retracted"
      ~ last_updated = "Thursday, 04-Apr-24 13:25:51 EEST" -> (known after apply)
        name         = "Ratetiger integration"
      ~ unique_email = "retracted@automation.instatus.com" -> (known after apply)
        # (6 unchanged attributes hidden)
    }
```

### Expected Behavior
Consecutive `terraform apply`s should finish without any pending changes

### Actual Behavior
Terraform want's to change resources perpetually.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create `instatus_component`
2. `terraform apply`
3. `terraform apply` again

**Comment by jarinom** [comment]
Strange things happened. I moved my `instatus_component` resources into modules and lazily recreated them instead of using `moved` blocks. This resolved the issue and now `terraform plan` doesn't show any changes.

How ever there's something broken in the group parameter, but I'll make an another issue out of it once I have more time.

**Comment by paydaycay** [comment]
Sorry for the delay. Why did you need to use `moved` blocks ? 
Could you tell me more about group parameter please ? If so, don't hesitate to open a new issue and I will take a look when having some time.

**Comment by jarinom** [comment]
I opened a new issue for the grouping issue.

Perpetual diff actually occurs if you leave out `status` parameter. Which is something you would wan't to do if you handle statuses out side of Terraform.
